const vm=require('vm'),fs=require('fs'),assert=require('assert');
const context={firebase:{initializeApp(){return{database(){return{ref(){return{on(){},once(){},transaction(){},set(){},update(){},child(){return this;},remove(){}};}};}};},database(){return this.initializeApp().database();}},document:{getElementById(){return{style:{},classList:{add(){},remove(){},toggle(){}},appendChild(){}}},querySelector(){return null},querySelectorAll(){return[]},addEventListener(){},createElement(){return{style:{},classList:{add(){},remove(){}}}}},window:{location:{search:'',href:''},localStorage:{getItem(){return null},setItem(){}},addEventListener(){},setTimeout,clearTimeout,alert(){}},console,Math,Date,JSON,RegExp,Array,Object,String,Number,Boolean,parseInt,isNaN,setTimeout,clearTimeout};context.window.document=context.document;context.window.firebase=context.firebase;context.global=context;
const sandbox=vm.createContext(context);['config.js','data.js', 'stages/stage-table.js','room-lifecycle.js','game.js', 'sha/sha-resolution.js','weapons.js','skills.js'].forEach(f=>vm.runInContext(fs.readFileSync(f,'utf8'),sandbox,{filename:f}));const R=s=>vm.runInContext(s,sandbox);R('tx=function(fn){return fn(__g)};mySeat=0;');const eq=()=>R('emptyEquips')();const p=(name,general)=>({name,general,hp:4,maxHp:4,hand:[],equips:eq(),delays:[],alive:true,chained:true});
const g={players:[p('李典','lidian'),p('甲','caocao'),p('乙','liubei')],deck:Array.from({length:8},(_,i)=>({name:'牌',suit:'♣',rank:i+1,id:'d'+i})),discard:[],log:[],phase:'play',turn:0,roundNum:1,gameMode:'ffa',pending:null};sandbox.__g=g;const thunder={name:'雷杀',suit:'♠',rank:7,id:'thunder'};
assert.strictEqual(R('dealDamage(__g,1,1,0,"雷杀","sha",'+JSON.stringify(thunder)+')'),true);assert.strictEqual(g.pending.type,'wangxiAsk');assert.strictEqual(g.pending.otherSeat,1);
R('respondWangxi(true)');assert.strictEqual(g.pending.type,'wangxiAsk');assert.strictEqual(g.pending.otherSeat,2);
R('respondWangxi(true)');assert.strictEqual(g.players[0].hand.length,2,'李典对两名连环角色各触发一次忘隙');assert.strictEqual(g.players[1].hand.length,1);assert.strictEqual(g.players[2].hand.length,1);assert.strictEqual(g.pending,null);
const data=fs.readFileSync('data.js','utf8');assert(data.includes('恂恂:摸牌阶段,你可以'));
console.log('wangxi chain tests: 9/9 passed; xunxun remains optional per skill text');
