const vm=require('vm'),fs=require('fs'),assert=require('assert');
const context={firebase:{initializeApp(){return{database(){return{ref(){return{on(){},once(){},transaction(){},set(){},update(){},child(){return this;},remove(){}};}};}};},database(){return this.initializeApp().database();}},document:{getElementById(){return{style:{},classList:{add(){},remove(){},toggle(){}},appendChild(){}}},querySelector(){return null},querySelectorAll(){return[]},addEventListener(){},createElement(){return{style:{},classList:{add(){},remove(){}}}}},window:{location:{search:'',href:''},localStorage:{getItem(){return null},setItem(){}},addEventListener(){},setTimeout,clearTimeout,alert(){}},console,Math,Date,JSON,RegExp,Array,Object,String,Number,Boolean,parseInt,isNaN,setTimeout,clearTimeout};
context.window.document=context.document;context.window.firebase=context.firebase;context.global=context;
const sandbox=vm.createContext(context);['config.js','data.js', 'stages/stage-table.js','room-lifecycle.js','game.js', 'sha/sha-resolution.js','weapons.js','skills.js'].forEach(f=>vm.runInContext(fs.readFileSync(f,'utf8'),sandbox,{filename:f}));
const R=s=>vm.runInContext(s,sandbox);R('tx=function(fn){return fn(__g)};mySeat=1;');const eq=()=>R('emptyEquips')();
const thunder={name:'雷杀',suit:'♠',rank:7,id:'thunder'};
const g={players:[{name:'颜良文丑',general:'yanliangwenchou',hp:4,maxHp:4,hand:[],equips:eq(),delays:[],alive:true},{name:'夏侯渊',general:'xiahouyuan',hp:4,maxHp:4,hand:[{name:'闪',suit:'♦',rank:2,id:'shan'}],equips:eq(),delays:[],alive:true}],deck:[],discard:[],log:[],phase:'respond',turn:0,roundNum:1,gameMode:'ffa',pending:{from:0,to:1,noShan:false,shaColor:'black',sourceCard:thunder}};sandbox.__g=g;
R('respondShan(false)');
assert.strictEqual(g.players[1].hp,3,'选择不闪后应受到1点雷电伤害');
assert.strictEqual(g.players[1].hand.length,1,'选择不闪不得强制消耗闪');
assert.strictEqual(g.pending,null);assert.strictEqual(g.phase,'play');
const ui=fs.readFileSync('render-controls.js','utf8');assert(ui.includes("b2.textContent='不闪（受伤）'"));assert(ui.includes("b2.onclick=()=>respondShan(false)"));
console.log('thunder sha decline tests: 6/6 passed');
